


local targetModule = require(game:GetService("Players").ameliacutie_xo.Backpack[".357 Magnum"].Setting["1"])
if setreadonly then setreadonly(targetModule, false) end

targetModule.AngleX_Min = 0 -- [PATCHED]
targetModule.Lifesteal = 99999 -- [PATCHED]
targetModule.MeleeCriticalDamageEnabled = 999999 -- [PATCHED]
targetModule.Spread = 0 -- [PATCHED]
targetModule.BaseDamage = 999999 -- [PATCHED]
targetModule.MeleeDamage = 999999 -- [PATCHED]
targetModule.Auto = false -- [PATCHED]
targetModule.ChargingTime = 0 -- [PATCHED]
targetModule.BulletSpeed = 90000 -- [PATCHED]
targetModule.HeadshotEnabled = 100 -- [PATCHED]
targetModule.BulletLifetime = 10 -- [PATCHED]
targetModule.AngleZ_Max = 0 -- [PATCHED]
targetModule.DelayBeforeFiring = 0 -- [PATCHED]
targetModule.EquipTime = 0 -- [PATCHED]
targetModule.BurstRate = 0 -- [PATCHED]
targetModule.Recoil = 0 -- [PATCHED]
targetModule.MeleeHeadshotEnabled = 100 -- [PATCHED]
targetModule.AngleX_Max = 0 -- [PATCHED]
targetModule.CriticalDamageEnabled = 999999 -- [PATCHED]
targetModule.ShotgunEnabled = true -- [PATCHED]
targetModule.Knockback = math.huge -- [PATCHED]
targetModule.SwitchTime = 0 -- [PATCHED]
targetModule.AmmoPerMag = 999999 -- [PATCHED]
targetModule.FireRate = 0 -- [PATCHED]
targetModule.SuperRicochet = true -- [PATCHED]
targetModule.MeleeCriticalDamageMultiplier = 999999 -- [PATCHED]
targetModule.RicochetAmount = 15 -- [PATCHED]
targetModule.ZeroDamageDistance = 999999 -- [PATCHED]
targetModule.AngleY_Max = 0 -- [PATCHED]
targetModule.DualFireEnabled = false -- [PATCHED]
targetModule.MeleeHeadshotDamageMultiplier = 999999 -- [PATCHED]
targetModule.CriticalDamageMultiplier = 999999 -- [PATCHED]
targetModule.TacticalReloadTime = 0 -- [PATCHED]
targetModule.DelayAfterFiring = 0 -- [PATCHED]
targetModule.ReduceSelfDamageOnAirOnly = 999999 -- [PATCHED]
targetModule.DamageBasedOnDistance = 999999 -- [PATCHED]
targetModule.DamageDropOffEnabled = 999999 -- [PATCHED]
targetModule.ReloadTime = 0 -- [PATCHED]
targetModule.BulletPerShot = 1 -- [PATCHED]
targetModule.FriendlyFire = true -- [PATCHED]
targetModule.AngleY_Min = 0 -- [PATCHED]
targetModule.SilenceEffect = false -- [PATCHED]
targetModule.Accuracy = 0 -- [PATCHED]
targetModule.LimitedAmmoEnabled = false -- [PATCHED]
targetModule.FullDamageDistance = 999999 -- [PATCHED]
targetModule.HeadshotDamageMultiplier = 999999 -- [PATCHED]
targetModule.AngleZ_Min = 0 -- [PATCHED]
targetModule.SelfDamageRedution = 999999 -- [PATCHED]

if setreadonly then setreadonly(targetModule, true) end
print('--> [Poison]: 1 has been neutralized.')
